services:
  sandbox-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: erlang-box-dev
    volumes:
      - .:/workspace:cached
    ports:
      - "5555:4000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - broker
    tty: true
  broker:
    image: rabbitmq:4.2.3-management
    hostname: my-rabbit
    container_name: rabbit-for-sandbox
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}